name: godo
description: A To-do to help you to manage your tasks swiftly with ease and gets you to "go do" it!
  anywhere, anytime !"
publish_to: 'none'

version: 1.0.0+1
isar_version: &isar_version 3.1.0+1

environment:
  sdk: ^3.5.3

dependencies:
  async_redux: ^24.0.2
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  get_it: ^8.0.2
  go_router: ^14.4.1
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  isar_generator: 3.1.0+1
  json_serializable: ^6.8.0
flutter:
  uses-material-design: true
